import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import TendinaMenu from "@/components/tendinaMenu";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
import SectionAbout from "@/components/sectionAbout";
import SectionSkills from "@/components/sectionSkills";
import SectionProject from "@/components/sectionProject";
import SectionWork from "@/components/sectionWork";
import Footer from "@/components/footer";
import { useEffect, useState } from "react";
import { PortfolioData } from "../../types/portfolio";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tendina, setTendina] = useState<boolean>(false);
  const [portfolioData, setPortfolioData] = useState<
    PortfolioData | undefined
  >();

  useEffect(() => {
    fetch("/api/static-data")
      .then((res) => res.json())
      .then((data) => setPortfolioData(data));
  }, []);

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TendinaMenu tendina={tendina} setTendina={setTendina} />
        <Navbar setTendina={setTendina} />
        <Hero
          userInfo={portfolioData?.userInfo}
          social={portfolioData?.social}
        />
        <SectionAbout userInfo={portfolioData?.userInfo} />
        <SectionSkills skills={portfolioData?.skills} />
        <SectionProject project={portfolioData?.project} />
        <SectionWork works={portfolioData?.works} />
        <Footer />
      </main>
    </>
  );
}
